/**
 * Context File Storage Utilities
 *
 * Handles saving Jira issue context files to disk for use with GitHub Copilot.
 * These files are stored in a configurable directory (default: .jira) and provide
 * rich context to Copilot for better assistance.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

/**
 * Save a context file to the configured location
 *
 * Creates the directory if it doesn't exist, saves the markdown content to a file
 * named after the issue key, and ensures the directory is added to .gitignore.
 *
 * @param issueKey - The Jira issue key (e.g., "PROJ-123")
 * @param markdown - The markdown content to save
 * @param contextFileLocation - Directory path relative to workspace root (e.g., ".jira")
 * @returns Promise that resolves to the absolute file path of the saved file
 * @throws Error if no workspace folder is open
 */
export async function saveContextFile(
  issueKey: string,
  markdown: string,
  contextFileLocation: string
): Promise<string> {
  // Get workspace root
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    throw new Error('No workspace folder open. Please open a workspace to use the "Investigate with Copilot" feature.');
  }

  // Build context directory path
  const contextDir = path.join(workspaceRoot, contextFileLocation);

  // Create directory if it doesn't exist
  if (!fs.existsSync(contextDir)) {
    fs.mkdirSync(contextDir, { recursive: true });
  }

  // Build file path
  const filePath = path.join(contextDir, `${issueKey}.md`);

  // Write file (overwrite if exists)
  fs.writeFileSync(filePath, markdown, 'utf-8');

  // Ensure .gitignore includes the context directory
  await ensureGitignore(workspaceRoot, contextFileLocation);

  return filePath;
}

/**
 * Ensure the context directory is added to .gitignore
 *
 * Checks if .gitignore exists and if it contains an entry for the context directory.
 * If not, adds the directory to .gitignore to prevent committing generated context files.
 *
 * @param workspaceRoot - The workspace root directory path
 * @param contextFileLocation - Directory path relative to workspace root
 */
async function ensureGitignore(workspaceRoot: string, contextFileLocation: string): Promise<void> {
  const gitignorePath = path.join(workspaceRoot, '.gitignore');

  // Read existing .gitignore or create empty string
  let gitignoreContent = '';
  if (fs.existsSync(gitignorePath)) {
    gitignoreContent = fs.readFileSync(gitignorePath, 'utf-8');
  }

  // Normalize the path for comparison (convert backslashes to forward slashes)
  const normalizedPath = contextFileLocation.replace(/\\/g, '/');

  // Check if the context directory is already in .gitignore
  // Look for exact match or with trailing slash
  const lines = gitignoreContent.split('\n');
  const hasEntry = lines.some(line => {
    const trimmed = line.trim();
    return trimmed === normalizedPath ||
           trimmed === `${normalizedPath}/` ||
           trimmed === `/${normalizedPath}` ||
           trimmed === `/${normalizedPath}/`;
  });

  if (!hasEntry) {
    // Add entry to .gitignore
    // Add newline if file doesn't end with one
    if (gitignoreContent.length > 0 && !gitignoreContent.endsWith('\n')) {
      gitignoreContent += '\n';
    }

    // Add a comment and the directory entry
    gitignoreContent += `\n# Jira context files for GitHub Copilot (generated by 42-Jira-Buddy)\n`;
    gitignoreContent += `${normalizedPath}/\n`;

    // Write back to .gitignore
    fs.writeFileSync(gitignorePath, gitignoreContent, 'utf-8');
  }
}

/**
 * Check if a context file exists for the given issue key
 *
 * @param issueKey - The Jira issue key
 * @param contextFileLocation - Directory path relative to workspace root
 * @returns Promise that resolves to true if file exists, false otherwise
 */
export async function contextFileExists(
  issueKey: string,
  contextFileLocation: string
): Promise<boolean> {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    return false;
  }

  const filePath = path.join(workspaceRoot, contextFileLocation, `${issueKey}.md`);
  return fs.existsSync(filePath);
}

/**
 * Get the path to a context file for the given issue key
 *
 * @param issueKey - The Jira issue key
 * @param contextFileLocation - Directory path relative to workspace root
 * @returns Promise that resolves to the absolute file path, or null if workspace is not open
 */
export async function getContextFilePath(
  issueKey: string,
  contextFileLocation: string
): Promise<string | null> {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    return null;
  }

  return path.join(workspaceRoot, contextFileLocation, `${issueKey}.md`);
}

/**
 * Delete a context file for the given issue key
 *
 * @param issueKey - The Jira issue key
 * @param contextFileLocation - Directory path relative to workspace root
 * @returns Promise that resolves to true if file was deleted, false if it didn't exist
 */
export async function deleteContextFile(
  issueKey: string,
  contextFileLocation: string
): Promise<boolean> {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    return false;
  }

  const filePath = path.join(workspaceRoot, contextFileLocation, `${issueKey}.md`);

  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    return true;
  }

  return false;
}

/**
 * Get the age of a context file in milliseconds
 *
 * Feature 7.7: Caching Investigation Results
 *
 * Returns the age of the context file based on its last modification time.
 * Returns null if the file doesn't exist.
 *
 * @param issueKey - The Jira issue key
 * @param contextFileLocation - Directory path relative to workspace root
 * @returns Promise that resolves to age in milliseconds, or null if file doesn't exist
 */
export async function getContextFileAge(
  issueKey: string,
  contextFileLocation: string
): Promise<number | null> {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    return null;
  }

  const filePath = path.join(workspaceRoot, contextFileLocation, `${issueKey}.md`);

  if (!fs.existsSync(filePath)) {
    return null;
  }

  const stats = fs.statSync(filePath);
  const age = Date.now() - stats.mtimeMs;
  return age;
}
